name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your default branch
  tags:
    - 'v*'  # This triggers the workflow when you push a version tag (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sagipael/docker-mailrelay:latest .
          docker tag ghcr.io/sagipael/docker-mailrelay:latest ghcr.io/sagipael/docker-mailrelay:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/sagipael/docker-mailrelay:latest
          docker push ghcr.io/sagipael/docker-mailrelay:${{ github.sha }}
